### ISSUE TITLE
zabbix sender packet length calculation

### ISSUE THREAD

**Issue by electrodyssey** [hengyunabc/zabbix-sender#10]
Hi
Packet length calculation in io.github.hengyunabc.zabbix.sender contains typo, it should be like below:

                (byte)(length & 0xFF),
                (byte)((length & 0xFF00) >> 8),
                (byte)((length & 0xFF0000) >> 16),
                (byte)((length & 0xFF000000) >> 24)

**Comment by hengyunabc** [comment]
The code from guava:

```java
// byte[] com.google.common.primitives.Ints.toByteArray(int value)
  public static byte[] toByteArray(int value) {
    return new byte[] {
      (byte) (value >> 24),
      (byte) (value >> 16),
      (byte) (value >> 8),
      (byte) value
    };
  }
```

**Comment by electrodyssey** [comment]
Sorry for disturbance. What I was trying to bring to your attention is that current code is erroneously calculating the length bytes. Value of AND mask is always 0xFF. Please check my suggestion below.
I'm sure that this works for Zabbix 2.x, but version 3.x would not accept such a packet.
Thank you for your attention.

current code:
		result[header.length] = (byte) (jsonBytes.length & 0xFF);
		result[header.length + 1] = (byte) ((jsonBytes.length >> 8)   & 0x00FF);
		result[header.length + 2] = (byte) ((jsonBytes.length >> 16) & 0x0000FF);
		result[header.length + 3] = (byte) ((jsonBytes.length >> 24) & 0x000000FF);

suggestion:

		result[header.length] = (byte) (jsonBytes.length & 0xFF);
		result[header.length + 1] = (byte) ((jsonBytes.length >> 8) &   0xFF00);
		result[header.length + 2] = (byte) ((jsonBytes.length >> 16) & 0xFF0000);
		result[header.length + 3] = (byte) ((jsonBytes.length >> 24) & 0xFF000000);

**Comment by hengyunabc** [comment]
Do you have test your suggestion code?

---

My test code:

```java
public class Test {

	public static void main(String[] args) {

		for (int i = 0; i < Integer.MAX_VALUE; ++i) {
			boolean equals = Arrays.equals(toBytes1(i), toBytes2(i));
			if (!equals) {
				System.err.println(i);
				System.exit(1);
			}
		}
	}

	public static byte[] toBytes1(int value) {
		byte[] result = new byte[4];

		result[0] = (byte) (value & 0xFF);
		result[1] = (byte) ((value >> 8) & 0x00FF);
		result[2] = (byte) ((value >> 16) & 0x0000FF);
		result[3] = (byte) ((value >> 24) & 0x000000FF);
		return result;
	}

	public static byte[] toBytes2(int value) {
		return new byte[] {
				(byte) value,
				(byte) (value >> 8),
				(byte) (value >> 16),
				(byte) (value >> 24) };
	}
}
```

**Comment by electrodyssey** [comment]
Dear Heng, I've tested and found that both methods gave a similar result, so there are no errors in your code. I was mislead by a different issue. Thanks for your attention and sorry for bothering you.

**Comment by hengyunabc** [comment]
Thanks.
