### ISSUE TITLE
zabbix-sender运行ZabbixSenderTest.test_LLD_rule方法,返回send fail，该如何排查问题呢？

### ISSUE THREAD

**Issue by zh-lizhi** [hengyunabc/zabbix-sender#2]
result:{"failed":1,"processed":0,"spentSeconds":4.7E-5,"total":1}
send fail!

**Comment by hengyunabc** [comment]
要先在zabbix server上创建好item，才可以发送成功。在zabbix server上有个地方可以看到接收到错误数据的。你可以从zabbix的界面上找找看。

完整的流程是用zabbix-api来创建item，然后再用zabbix-sender来发送数据。当然item可以在web界面上直接手工创建。

**Comment by zh-lizhi** [comment]
“在zabbix server上有个地方可以看到接收到错误数据的。你可以从zabbix的界面上找找看。”
能描述详细点吗？
具体在哪个地方……谢谢

**Comment by zh-lizhi** [comment]
zabbix-sender-master和zabbix-api-master在性能优化方面，有哪些地方可以改进吗？
假如有大量item都需要调用zabbix-sender，发送数据到server……

**Comment by hengyunabc** [comment]
界面那个我忘记了。 zabbix-sender的发送速度取决于zabbix-server的接收速度。zabbix-sender只是发送数据，不会有性能问题。
zabbix好像还有一种中继节点，纯接收数据的，再转发给zabbix-server。

**Comment by zh-lizhi** [comment]
result:{"failed":0,"processed":1,"spentSeconds":1.18E-4,"total":1}
send success!

zabbix-sender 终于调通啦（现在页面创建的item）
但是在哪里看具体数据呢？
在item列表没看到……

**Comment by zh-lizhi** [comment]
result:{"failed":0,"processed":1,"spentSeconds":1.18E-4,"total":1}
send success!

zabbix-sender 终于调通啦（现在页面创建的item）
但是在哪里看具体数据呢？
在菜单中 Monitoring → Latest data 没有查看到

**Comment by hengyunabc** [comment]
数据不能直接被看到，可以创建一个图表，然后把item选上，然后就可以显示了。

**Comment by zh-lizhi** [comment]
在 Monitoring → Latest data
根据主机过滤下，然后找到创建的item，点历史记录可以看到数据……
在请教一个问题，item数据进来后，怎么报警呢？
比如我这个item是的value是文本的……

**Comment by hengyunabc** [comment]
不好意思，报警我不太清楚，可以看下zabbix的文档，相关的资料应该有不少。

**Comment by zh-lizhi** [comment]
能看下我在zabbix-api-master反馈的问题吗？
调api登陆有问题，其他的接口也不行……
