### ISSUE TITLE
timestamp problem with zabbix 3.0

### ISSUE THREAD

**Issue by eittherr** [hengyunabc/zabbix-sender#3]
Hi!

I've discovered that Zabbix server 3.01 doesn't accept the data from ZabbixSender correctly.
The problem is that ZabbixSender always send  timestamp for the whole request as **System.currentTimeMillis()**, though Unix timestamp (time in seconds) is required for zabbix items. Older versions of server accepted this, the new one does not.

I replaced with **System.currentTimeMillis()/1000**, and now it works fine.

**Comment by tgibson11** [comment]
Wow...god bless you @eittherr!  I've been beating my head against a wall trying to figure out what changed and why my Zabbix log4j appender stopped working on 3.0.  Got to love the lack of documentation from Zabbix.  Thank you for this.

**Comment by giovannimele** [comment]
Hello, 
is there a plan to do an official release to correct this problem?

**Comment by hengyunabc** [comment]
Thank you very much. @eittherr 

@giovannimele Zabbix sender version 0.0.2 fixed this issue. I have tested it with zabbix server 2.4/3.0.
