### ISSUE TITLE
Zabbix-sender still not compatible with Zabbix 3.x

### ISSUE THREAD

**Issue by giovannimele** [hengyunabc/zabbix-sender#5]
Hello,

data sent with Zabbix sender still set the clock in ms since UNIX epoch instead of putting it in seconds. In consequence, it doesn't work with zabbix 3.x.

You already corrected something in a previous patch, but it seems class DataObject and method build() must also be patched. This method still sets the clock in ms instead of seconds.

public DataObject build() {
  if (clock == null) {
    clock = System.currentTimeMillis()**/1000**;
  }
  return new DataObject(clock, host, key, value);
}

Would it be possible to fix this as soon as possible? I'd like to integrate your code in our application.

Thx

Giovanni

**Comment by hengyunabc** [comment]
Thanks you very much, version 0.0.3 release has been push to maven center.
